# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\DevGim\desert\suffer\resources\dialog_manual_viewl.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogManual(object):
    def setupUi(self, DialogManual):
        DialogManual.setObjectName("DialogManual")
        DialogManual.resize(351, 242)
        self.gridLayout_2 = QtWidgets.QGridLayout(DialogManual)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(DialogManual)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout.setObjectName("gridLayout")
        self.listView = QtWidgets.QListView(self.tab_3)
        self.listView.setGridSize(QtCore.QSize(2, 10))
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 0, 0, 6, 1)
        self.radioButton = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 0, 1, 1, 2)
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 0, 3, 1, 2)
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 6, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.tab_3)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 3)
        self.pushButton = QtWidgets.QPushButton(self.tab_3)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 5, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 1, 1, 4)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 5, 1, 2)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 3, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 3, 2, 1, 4)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 3, 6, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 1, 1, 3)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 4, 4, 1, 3)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 5, 1, 1, 3)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 5, 4, 1, 3)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(DialogManual)
        self.tabWidget.setCurrentIndex(2)
        self.radioButton.clicked['bool'].connect(self.radioButton_2.setChecked)
        self.radioButton_2.clicked['bool'].connect(self.radioButton.setChecked)
        QtCore.QMetaObject.connectSlotsByName(DialogManual)

    def retranslateUi(self, DialogManual):
        _translate = QtCore.QCoreApplication.translate
        DialogManual.setWindowTitle(_translate("DialogManual", "Dialog"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("DialogManual", "잔고"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("DialogManual", "매도"))
        self.radioButton.setText(_translate("DialogManual", "현금"))
        self.radioButton_2.setText(_translate("DialogManual", "신용"))
        self.label.setText(_translate("DialogManual", "증40%"))
        self.pushButton.setText(_translate("DialogManual", "현금"))
        self.pushButton_2.setText(_translate("DialogManual", "미수"))
        self.pushButton_3.setText(_translate("DialogManual", "-"))
        self.pushButton_4.setText(_translate("DialogManual", "+"))
        self.label_2.setText(_translate("DialogManual", "금액매수"))
        self.pushButton_5.setText(_translate("DialogManual", "계산"))
        self.pushButton_6.setText(_translate("DialogManual", "현금매수"))
        self.pushButton_7.setText(_translate("DialogManual", "시장가매수"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("DialogManual", "매수"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("DialogManual", "정정/취소"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("DialogManual", "주식체결"))

